const VIDEO_IDS = {
  "Supino reto com barra": "50RSzhMG5Hc",
  "Supino inclinado com halteres": "Fa-X2ByLHaY",
  "Crucifixo na maquina": "9BEQWr0u-ac",
  "Supino articulado": "KNuTH1LRq0Y",
  "Crossover na polia": "nuTuKjcQRHg",
  "Flexao tradicional": "pRzxpe5_LLk",
  "Flexao inclinada": "so5nuzZWwmI",
  "Flexao declinada": "FRJmagk0qgU",
  "Supino no chao com halteres": "qWLmjXthx7g",
  "Crucifixo com elastico": "u440fUv33XE",
  "Puxada frontal": "ftcql3-AMRs",
  "Remada curvada": "cMQpvkZGQrE",
  "Remada baixa": "fZzybnfRhqA",
  "Pulldown na corda": "GDhW19yQrJI",
  "Remada unilateral com halter": "eeg6REnybpI",
  "Remada com elastico": "TNO7QaRdNp4",
  Superman: "vDXe2eBowUg",
  "Pulldown com elastico": "F4EUo0CJVro",
  "Remada invertida em mesa": "HJ2q4VjTbKE",
  "Anjo reverso no chao": "5QqGzrqNeSg",
  "Agachamento livre": "8V2SwkHTLek",
  "Leg press": "lHZUF_s3q9c",
  "Cadeira extensora": "u68RNdfZymA",
  "Afundo guiado": "poAnWrA7DSU",
  "Hack squat": "x0waoZh8pnk",
  "Agachamento com peso corporal": "9qwvgBHdml0",
  "Agachamento sumo": "9qwvgBHdml0",
  "Afundo alternado": "ejVZHao6psY",
  "Agachamento com salto": "PHrKn4JaAG4",
  "Agachamento goblet": "ccLGfT51WHw",
  "Elevacao pelvica com barra": "ptK0azwOXwM",
  "Cadeira abdutora": "GljAOyT5xLI",
  "Coice no cabo": "ToE6yT5pHZ0",
  "Glute bridge guiado": "1satDE63Bwc",
  "Step up com halteres": "VQ3idU0WSWg",
  "Elevacao pelvica no chao": "ptK0azwOXwM",
  "Coice com elastico": "kU3rpk2l2M0",
  "Abducao lateral com mini band": "8NWsDeYI7Og",
  "Ponte unilateral": "0e1SXFq806U",
  "Step up em cadeira": "S3Af98IwVcs",
  "Desenvolvimento militar": "mtNvpLOKnZo",
  "Elevacao lateral": "nhQ4mdk0TmM",
  "Crucifixo invertido": "yV1_3qfmEG8",
  "Arnold press": "O3nHTDcdJDo",
  "Remada alta na barra": "csF_uw7niTI",
  "Elevacao lateral com garrafas": "5uLC4EOJ11Q",
  "Desenvolvimento com elastico": "c-E72n42kD0",
  "Crucifixo invertido com elastico": "ja34nPrn2qU",
  "Pike push up": "eG20L9cl81w",
  "Elevacao frontal com mochila": "ZSDBvuLGrMk",
  "Rosca direta na barra": "ojlJslnaae4",
  "Rosca martelo": "GilFwBs_kOs",
  "Rosca concentrada": "Qm4NdQttdi8",
  "Rosca Scott": "faBk2akE0mQ",
  "Rosca na polia baixa": "M6CPOlx7n9g",
  "Rosca com elastico": "ogyezynh-DU",
  "Rosca martelo com garrafas": "GilFwBs_kOs",
  "Rosca isometrica com toalha": "LQpnW4DPb5Y",
  "Chin up assistido": "Oi3bW9nQmGI",
  "Rosca concentrada com mochila": "w4APwTMjDA8",
  "Triceps pulley": "Xowd3iqdBS0",
  "Triceps frances": "TkGyrH6EQK4",
  "Mergulho entre bancos": "p_DeBmkbCUc",
  "Triceps corda acima da cabeca": "aNr8yjs34nM",
  "Triceps testa": "0jMF0o0DdbA",
  "Triceps banco": "p_DeBmkbCUc",
  "Extensao de triceps com elastico": "mpVyaCwZrBg",
  "Flexao diamante": "DfsWjEThmLY",
  "Coice de triceps com halter": "JKrjAtGqkxU",
  "Triceps frances com mochila": "TkGyrH6EQK4",
  "Caminhada inclinada": "86YTZYxQgS8",
  "Bicicleta intervalada": "RKi8h4aL75E",
  "Eliptico moderado": "KjoCtuZfew4",
  "Escada ergometrica": "LUoyfc9nUGs",
  "Remo ergometrico": "yaxveBJGoy8",
  "Pular corda": "0bRV-Nz381Y",
  Polichinelos: "RF9Jj6H160c",
  "Corrida estacionaria": "FT0fyIr8aJc",
  "Burpee controlado": "aFSpzKujvZk",
  "Subida em degrau": "btF1VEFQG18",
};

const makeVideoUrl = (name) =>
  VIDEO_IDS[name]
    ? `https://www.youtube.com/watch?v=${VIDEO_IDS[name]}`
    : `https://www.youtube.com/results?search_query=${encodeURIComponent(`${name} execucao correta`)}`;

function item({
  name,
  muscleGroup,
  goal = "geral",
  environment,
  calories,
  equipment,
  description,
}) {
  return {
    name,
    muscleGroup,
    goal,
    environment,
    calories,
    equipment,
    description,
    videoUrl: makeVideoUrl(name),
  };
}

export const seedExercises = [
  item({ name: "Supino reto com barra", muscleGroup: "peito", goal: "definicao", environment: "academia", calories: 48, equipment: "Barra e banco", description: "Base de peitoral para academia." }),
  item({ name: "Supino inclinado com halteres", muscleGroup: "peito", goal: "definicao", environment: "academia", calories: 46, equipment: "Halteres e banco", description: "Maior enfase na parte superior do peitoral." }),
  item({ name: "Crucifixo na maquina", muscleGroup: "peito", goal: "geral", environment: "academia", calories: 34, equipment: "Peck deck", description: "Trabalho isolado de peitoral com controle." }),
  item({ name: "Supino articulado", muscleGroup: "peito", goal: "geral", environment: "academia", calories: 43, equipment: "Maquina articulada", description: "Opcao guiada para peitoral." }),
  item({ name: "Crossover na polia", muscleGroup: "peito", goal: "perda_de_peso", environment: "academia", calories: 36, equipment: "Polias", description: "Finalizacao metabolica para peitoral." }),
  item({ name: "Flexao tradicional", muscleGroup: "peito", goal: "geral", environment: "casa", calories: 34, equipment: "Peso corporal", description: "Exercicio classico para peito em casa." }),
  item({ name: "Flexao inclinada", muscleGroup: "peito", goal: "geral", environment: "casa", calories: 28, equipment: "Cadeira ou sofa", description: "Versao regressiva para peitoral." }),
  item({ name: "Flexao declinada", muscleGroup: "peito", goal: "definicao", environment: "casa", calories: 39, equipment: "Banco ou cama", description: "Mais carga relativa para o peitoral." }),
  item({ name: "Supino no chao com halteres", muscleGroup: "peito", goal: "definicao", environment: "casa", calories: 38, equipment: "Halteres", description: "Opcao segura de peitoral no solo." }),
  item({ name: "Crucifixo com elastico", muscleGroup: "peito", goal: "geral", environment: "casa", calories: 30, equipment: "Elastico", description: "Boa alternativa para abertura de peitoral em casa." }),

  item({ name: "Puxada frontal", muscleGroup: "costas", goal: "geral", environment: "academia", calories: 43, equipment: "Polia alta", description: "Puxada vertical para dorsais." }),
  item({ name: "Remada curvada", muscleGroup: "costas", goal: "definicao", environment: "academia", calories: 50, equipment: "Barra", description: "Exercicio composto para costas." }),
  item({ name: "Remada baixa", muscleGroup: "costas", goal: "geral", environment: "academia", calories: 41, equipment: "Polia baixa", description: "Remada com mais estabilidade." }),
  item({ name: "Pulldown na corda", muscleGroup: "costas", goal: "perda_de_peso", environment: "academia", calories: 33, equipment: "Polia", description: "Finalizacao para dorsais." }),
  item({ name: "Remada unilateral com halter", muscleGroup: "costas", goal: "geral", environment: "academia", calories: 38, equipment: "Halter e banco", description: "Ajusta assimetrias de costas." }),
  item({ name: "Remada com elastico", muscleGroup: "costas", goal: "geral", environment: "casa", calories: 29, equipment: "Elastico", description: "Alternativa simples para dorsais em casa." }),
  item({ name: "Superman", muscleGroup: "costas", goal: "geral", environment: "casa", calories: 21, equipment: "Peso corporal", description: "Ativa extensores e estabilizadores." }),
  item({ name: "Pulldown com elastico", muscleGroup: "costas", goal: "definicao", environment: "casa", calories: 27, equipment: "Elastico preso acima", description: "Simula a puxada alta em casa." }),
  item({ name: "Remada invertida em mesa", muscleGroup: "costas", goal: "definicao", environment: "casa", calories: 35, equipment: "Mesa resistente", description: "Puxada horizontal com peso corporal." }),
  item({ name: "Anjo reverso no chao", muscleGroup: "costas", goal: "geral", environment: "casa", calories: 18, equipment: "Peso corporal", description: "Trabalho de parte alta das costas." }),

  item({ name: "Agachamento livre", muscleGroup: "pernas", goal: "geral", environment: "academia", calories: 62, equipment: "Barra", description: "Base de membros inferiores." }),
  item({ name: "Leg press", muscleGroup: "pernas", goal: "definicao", environment: "academia", calories: 57, equipment: "Leg press", description: "Controle de carga para pernas." }),
  item({ name: "Cadeira extensora", muscleGroup: "pernas", goal: "geral", environment: "academia", calories: 31, equipment: "Extensora", description: "Isolamento de quadriceps." }),
  item({ name: "Afundo guiado", muscleGroup: "pernas", goal: "perda_de_peso", environment: "academia", calories: 45, equipment: "Smith ou halteres", description: "Opcao metabolica para pernas." }),
  item({ name: "Hack squat", muscleGroup: "pernas", goal: "definicao", environment: "academia", calories: 54, equipment: "Hack machine", description: "Trabalho controlado para quadriceps." }),
  item({ name: "Agachamento com peso corporal", muscleGroup: "pernas", goal: "geral", environment: "casa", calories: 36, equipment: "Peso corporal", description: "Versao acessivel para pernas." }),
  item({ name: "Agachamento sumo", muscleGroup: "pernas", goal: "geral", environment: "casa", calories: 39, equipment: "Peso corporal ou halter", description: "Foco interno de coxa e estabilidade." }),
  item({ name: "Afundo alternado", muscleGroup: "pernas", goal: "perda_de_peso", environment: "casa", calories: 44, equipment: "Peso corporal", description: "Boa opcao para condicionamento." }),
  item({ name: "Agachamento com salto", muscleGroup: "pernas", goal: "perda_de_peso", environment: "casa", calories: 50, equipment: "Peso corporal", description: "Versao pliometrica para pernas." }),
  item({ name: "Agachamento goblet", muscleGroup: "pernas", goal: "definicao", environment: "casa", calories: 42, equipment: "Halter ou mochila", description: "Mais carga sem precisar de barra." }),

  item({ name: "Elevacao pelvica com barra", muscleGroup: "gluteos", goal: "geral", environment: "academia", calories: 38, equipment: "Barra e banco", description: "Exercicio forte para gluteos." }),
  item({ name: "Cadeira abdutora", muscleGroup: "gluteos", goal: "definicao", environment: "academia", calories: 29, equipment: "Maquina abdutora", description: "Gluteo medio e estabilidade." }),
  item({ name: "Coice no cabo", muscleGroup: "gluteos", goal: "geral", environment: "academia", calories: 31, equipment: "Polia baixa", description: "Isolamento de gluteos." }),
  item({ name: "Glute bridge guiado", muscleGroup: "gluteos", goal: "geral", environment: "academia", calories: 34, equipment: "Smith", description: "Opcao guiada para quadril." }),
  item({ name: "Step up com halteres", muscleGroup: "gluteos", goal: "perda_de_peso", environment: "academia", calories: 43, equipment: "Caixa e halteres", description: "Subida unilateral com forte recrutamento." }),
  item({ name: "Elevacao pelvica no chao", muscleGroup: "gluteos", goal: "geral", environment: "casa", calories: 28, equipment: "Peso corporal", description: "Base para gluteos em casa." }),
  item({ name: "Coice com elastico", muscleGroup: "gluteos", goal: "geral", environment: "casa", calories: 24, equipment: "Mini band", description: "Isolamento para gluteos com elastico." }),
  item({ name: "Abducao lateral com mini band", muscleGroup: "gluteos", goal: "definicao", environment: "casa", calories: 22, equipment: "Mini band", description: "Gluteo medio e estabilidade." }),
  item({ name: "Ponte unilateral", muscleGroup: "gluteos", goal: "definicao", environment: "casa", calories: 27, equipment: "Peso corporal", description: "Foco unilateral de gluteos." }),
  item({ name: "Step up em cadeira", muscleGroup: "gluteos", goal: "perda_de_peso", environment: "casa", calories: 37, equipment: "Degrau ou cadeira firme", description: "Subida para gluteos e pernas." }),

  item({ name: "Desenvolvimento militar", muscleGroup: "ombros", goal: "definicao", environment: "academia", calories: 37, equipment: "Barra ou halteres", description: "Composto principal de ombros." }),
  item({ name: "Elevacao lateral", muscleGroup: "ombros", goal: "geral", environment: "academia", calories: 24, equipment: "Halteres", description: "Isolamento lateral de deltoides." }),
  item({ name: "Crucifixo invertido", muscleGroup: "ombros", goal: "geral", environment: "academia", calories: 26, equipment: "Halteres ou peck deck", description: "Foco em deltoide posterior." }),
  item({ name: "Arnold press", muscleGroup: "ombros", goal: "definicao", environment: "academia", calories: 33, equipment: "Halteres", description: "Press com grande amplitude." }),
  item({ name: "Remada alta na barra", muscleGroup: "ombros", goal: "perda_de_peso", environment: "academia", calories: 32, equipment: "Barra", description: "Trabalho combinado de deltoides." }),
  item({ name: "Elevacao lateral com garrafas", muscleGroup: "ombros", goal: "geral", environment: "casa", calories: 18, equipment: "Garrafas ou halteres", description: "Versao simples para ombros." }),
  item({ name: "Desenvolvimento com elastico", muscleGroup: "ombros", goal: "definicao", environment: "casa", calories: 24, equipment: "Elastico", description: "Press acima da cabeca em casa." }),
  item({ name: "Crucifixo invertido com elastico", muscleGroup: "ombros", goal: "geral", environment: "casa", calories: 20, equipment: "Elastico", description: "Deltoide posterior sem maquinas." }),
  item({ name: "Pike push up", muscleGroup: "ombros", goal: "definicao", environment: "casa", calories: 30, equipment: "Peso corporal", description: "Empurrada vertical com peso corporal." }),
  item({ name: "Elevacao frontal com mochila", muscleGroup: "ombros", goal: "geral", environment: "casa", calories: 19, equipment: "Mochila ou halter", description: "Foco na porcao anterior do ombro." }),

  item({ name: "Rosca direta na barra", muscleGroup: "biceps", goal: "definicao", environment: "academia", calories: 22, equipment: "Barra", description: "Classico para biceps." }),
  item({ name: "Rosca martelo", muscleGroup: "biceps", goal: "geral", environment: "academia", calories: 21, equipment: "Halteres", description: "Trabalho de biceps e antebraco." }),
  item({ name: "Rosca concentrada", muscleGroup: "biceps", goal: "geral", environment: "academia", calories: 20, equipment: "Halter", description: "Melhora a conexao muscular." }),
  item({ name: "Rosca Scott", muscleGroup: "biceps", goal: "definicao", environment: "academia", calories: 23, equipment: "Banco Scott", description: "Amplitude guiada de biceps." }),
  item({ name: "Rosca na polia baixa", muscleGroup: "biceps", goal: "perda_de_peso", environment: "academia", calories: 24, equipment: "Polia baixa", description: "Mantem tensao continua." }),
  item({ name: "Rosca com elastico", muscleGroup: "biceps", goal: "geral", environment: "casa", calories: 17, equipment: "Elastico", description: "Opcao pratica para biceps." }),
  item({ name: "Rosca martelo com garrafas", muscleGroup: "biceps", goal: "geral", environment: "casa", calories: 16, equipment: "Garrafas ou halteres", description: "Trabalho simples de biceps." }),
  item({ name: "Rosca isometrica com toalha", muscleGroup: "biceps", goal: "geral", environment: "casa", calories: 14, equipment: "Toalha", description: "Isometria para biceps sem peso." }),
  item({ name: "Chin up assistido", muscleGroup: "biceps", goal: "definicao", environment: "casa", calories: 31, equipment: "Barra fixa e apoio", description: "Puxada vertical com foco em biceps." }),
  item({ name: "Rosca concentrada com mochila", muscleGroup: "biceps", goal: "definicao", environment: "casa", calories: 18, equipment: "Mochila", description: "Carga adaptada em casa." }),

  item({ name: "Triceps pulley", muscleGroup: "triceps", goal: "geral", environment: "academia", calories: 23, equipment: "Polia alta", description: "Exercicio estavel de triceps." }),
  item({ name: "Triceps frances", muscleGroup: "triceps", goal: "definicao", environment: "academia", calories: 24, equipment: "Halter ou barra W", description: "Foco na cabeca longa." }),
  item({ name: "Mergulho entre bancos", muscleGroup: "triceps", goal: "geral", environment: "academia", calories: 28, equipment: "Bancos", description: "Opcao funcional para triceps." }),
  item({ name: "Triceps corda acima da cabeca", muscleGroup: "triceps", goal: "definicao", environment: "academia", calories: 25, equipment: "Polia com corda", description: "Alongamento maior do triceps." }),
  item({ name: "Triceps testa", muscleGroup: "triceps", goal: "perda_de_peso", environment: "academia", calories: 26, equipment: "Barra W", description: "Boa intensidade para triceps." }),
  item({ name: "Triceps banco", muscleGroup: "triceps", goal: "geral", environment: "casa", calories: 24, equipment: "Cadeira ou sofa", description: "Versao acessivel de triceps em casa." }),
  item({ name: "Extensao de triceps com elastico", muscleGroup: "triceps", goal: "geral", environment: "casa", calories: 19, equipment: "Elastico", description: "Triceps em casa com boa tensao." }),
  item({ name: "Flexao diamante", muscleGroup: "triceps", goal: "definicao", environment: "casa", calories: 29, equipment: "Peso corporal", description: "Empurrada fechada para triceps." }),
  item({ name: "Coice de triceps com halter", muscleGroup: "triceps", goal: "definicao", environment: "casa", calories: 18, equipment: "Halter ou garrafa", description: "Isolamento de triceps." }),
  item({ name: "Triceps frances com mochila", muscleGroup: "triceps", goal: "geral", environment: "casa", calories: 20, equipment: "Mochila", description: "Opcao adaptada sem academia." }),

  item({ name: "Caminhada inclinada", muscleGroup: "cardio", goal: "perda_de_peso", environment: "academia", calories: 72, equipment: "Esteira", description: "Aerobico de baixo impacto." }),
  item({ name: "Bicicleta intervalada", muscleGroup: "cardio", goal: "perda_de_peso", environment: "academia", calories: 68, equipment: "Bike ergometrica", description: "Intervais moderados para gasto calorico." }),
  item({ name: "Eliptico moderado", muscleGroup: "cardio", goal: "geral", environment: "academia", calories: 64, equipment: "Eliptico", description: "Boa opcao de cardio guiado." }),
  item({ name: "Escada ergometrica", muscleGroup: "cardio", goal: "definicao", environment: "academia", calories: 76, equipment: "Stair climber", description: "Cardio forte de academia." }),
  item({ name: "Remo ergometrico", muscleGroup: "cardio", goal: "geral", environment: "academia", calories: 70, equipment: "Remo", description: "Cardio global com forte demanda energetica." }),
  item({ name: "Pular corda", muscleGroup: "cardio", goal: "geral", environment: "casa", calories: 80, equipment: "Corda", description: "Cardio intenso em pouco espaco." }),
  item({ name: "Polichinelos", muscleGroup: "cardio", goal: "perda_de_peso", environment: "casa", calories: 45, equipment: "Peso corporal", description: "Cardio simples para casa." }),
  item({ name: "Corrida estacionaria", muscleGroup: "cardio", goal: "geral", environment: "casa", calories: 52, equipment: "Peso corporal", description: "Corrida no lugar para elevar frequencia cardiaca." }),
  item({ name: "Burpee controlado", muscleGroup: "cardio", goal: "perda_de_peso", environment: "casa", calories: 74, equipment: "Peso corporal", description: "Movimento global e intenso." }),
  item({ name: "Subida em degrau", muscleGroup: "cardio", goal: "geral", environment: "casa", calories: 49, equipment: "Degrau ou escada", description: "Aerobico continuo com baixo custo." }),
];
