import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f5efe8",
  },
  loadingScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f5efe8",
  },
  loadingTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1f1f1f",
  },
  loadingText: {
    marginTop: 8,
    color: "#6d6a66",
    fontSize: 16,
  },
  authScreen: {
    flexGrow: 1,
    padding: 24,
    justifyContent: "center",
    gap: 18,
  },
  authBrandBlock: {
    alignItems: "center",
    gap: 8,
  },
  authBrand: {
    color: "#e86b35",
    fontWeight: "800",
    fontSize: 15,
    textTransform: "uppercase",
    letterSpacing: 1.4,
  },
  authBrandTitle: {
    color: "#1f1f1f",
    fontSize: 30,
    fontWeight: "800",
    textAlign: "center",
  },
  authBrandText: {
    color: "#6d6964",
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    maxWidth: 320,
  },
  authCard: {
    backgroundColor: "#fff",
    borderRadius: 28,
    padding: 22,
    shadowColor: "#a58f7d",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 2,
  },
  authSwitch: {
    alignSelf: "center",
    marginTop: 10,
    paddingVertical: 8,
  },
  authSwitchText: {
    color: "#1f4037",
    fontSize: 14,
    fontWeight: "700",
  },
  content: {
    padding: 18,
    paddingBottom: 120,
    gap: 16,
  },
  registrationContainer: {
    padding: 18,
    gap: 16,
    paddingBottom: 48,
  },
  heroCard: {
    backgroundColor: "#1f4037",
    borderRadius: 28,
    padding: 22,
  },
  heroEyebrow: {
    color: "#f4b77b",
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  heroTitle: {
    marginTop: 10,
    color: "#fff",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "800",
  },
  heroText: {
    marginTop: 10,
    color: "#dde6df",
    fontSize: 15,
    lineHeight: 22,
  },
  appHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 4,
    gap: 12,
  },
  brand: {
    color: "#e86b35",
    fontWeight: "800",
    fontSize: 14,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  headerTitle: {
    color: "#1f1f1f",
    fontSize: 27,
    fontWeight: "800",
    marginTop: 4,
  },
  headerSubtitle: {
    color: "#6c6761",
    fontSize: 14,
    marginTop: 4,
  },
  headerAction: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#efd8c3",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  headerActionText: {
    color: "#6b513d",
    fontWeight: "700",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 18,
    shadowColor: "#a58f7d",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 2,
  },
  highlightCard: {
    backgroundColor: "#fff4eb",
    borderWidth: 1,
    borderColor: "#f2ceb0",
  },
  highlightCardAlt: {
    backgroundColor: "#edf6f3",
    borderWidth: 1,
    borderColor: "#cfe1db",
  },
  highlightEyebrow: {
    color: "#a45a2f",
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  highlightTitle: {
    color: "#1f1f1f",
    fontSize: 23,
    fontWeight: "800",
    marginTop: 6,
  },
  highlightText: {
    color: "#5b524b",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 22,
    color: "#1f1f1f",
    fontWeight: "800",
  },
  sectionSubtitle: {
    marginTop: 4,
    color: "#6d6964",
    lineHeight: 21,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1f1f1f",
  },
  cardMiniTitle: {
    fontSize: 13,
    color: "#7b736d",
    fontWeight: "700",
  },
  cardBody: {
    color: "#59544f",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  field: {
    marginBottom: 14,
  },
  fieldLabel: {
    fontSize: 14,
    color: "#4b4641",
    fontWeight: "700",
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#e7d8ca",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: "#fffaf6",
    color: "#1f1f1f",
    fontSize: 15,
  },
  inputMultiline: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  segmentedWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  pill: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#e4d4c4",
    backgroundColor: "#fffaf6",
  },
  pillActive: {
    borderColor: "#1f4037",
    backgroundColor: "#1f4037",
  },
  pillText: {
    color: "#5f574f",
    fontWeight: "700",
    fontSize: 13,
  },
  pillTextActive: {
    color: "#fff",
  },
  buttonRow: {
    flexDirection: "row",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 6,
  },
  button: {
    minHeight: 46,
    paddingHorizontal: 18,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonCompact: {
    flex: 1,
    minHeight: 42,
    paddingHorizontal: 10,
  },
  buttonPrimary: {
    backgroundColor: "#e86b35",
  },
  buttonSecondary: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e0d1c2",
  },
  buttonText: {
    fontWeight: "800",
    fontSize: 14,
  },
  buttonTextCompact: {
    fontSize: 12,
  },
  buttonPrimaryText: {
    color: "#fff",
  },
  buttonSecondaryText: {
    color: "#5a5149",
  },
  metricsRow: {
    flexDirection: "row",
    gap: 12,
  },
  metricCard: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: "#ece1d4",
  },
  metricTitle: {
    color: "#6c655f",
    fontWeight: "700",
    fontSize: 13,
  },
  metricValue: {
    color: "#1f1f1f",
    fontWeight: "800",
    fontSize: 24,
    marginTop: 8,
  },
  metricSubtitle: {
    color: "#7a736d",
    fontSize: 13,
    marginTop: 6,
    lineHeight: 18,
  },
  workoutHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  workoutHeaderLeft: {
    flex: 1,
  },
  workoutSummaryCard: {
    marginTop: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#efe2d6",
    backgroundColor: "#faf6f2",
    padding: 16,
    gap: 8,
  },
  workoutSummaryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  workoutLabel: {
    color: "#e86b35",
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.9,
  },
  workoutTitle: {
    color: "#1f1f1f",
    fontSize: 19,
    fontWeight: "800",
    marginTop: 5,
  },
  workoutFocus: {
    color: "#6d6762",
    marginTop: 6,
    lineHeight: 20,
  },
  workoutGuidance: {
    color: "#4f4a45",
    marginTop: 10,
    lineHeight: 21,
  },
  workoutSummaryText: {
    color: "#625b54",
    lineHeight: 20,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    minWidth: 104,
    alignItems: "center",
  },
  statusBadgeActive: {
    backgroundColor: "#1f4037",
    borderColor: "#1f4037",
  },
  statusBadgePending: {
    backgroundColor: "#fff7eb",
    borderColor: "#f0d7bc",
  },
  statusBadgeDone: {
    backgroundColor: "#eef8f4",
    borderColor: "#cde4da",
  },
  statusBadgeText: {
    color: "#675d53",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "center",
  },
  statusBadgeTextActive: {
    color: "#fff",
  },
  backLink: {
    alignSelf: "flex-start",
    marginBottom: 14,
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#2c6e63",
    fontWeight: "800",
  },
  tagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  infoNote: {
    color: "#4f4a45",
    marginTop: 12,
    lineHeight: 21,
    backgroundColor: "#fbf4ee",
    borderRadius: 14,
    padding: 12,
  },
  exerciseItem: {
    marginTop: 14,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#faf6f2",
    borderWidth: 1,
    borderColor: "#efe3d7",
    gap: 12,
  },
  exerciseItemDone: {
    backgroundColor: "#eef8f4",
    borderColor: "#cce4da",
  },
  exerciseItemPartial: {
    backgroundColor: "#fff7eb",
    borderColor: "#f4d6b6",
  },
  exerciseItemLocked: {
    opacity: 0.82,
  },
  exerciseTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  exerciseInfo: {
    flex: 1,
  },
  exerciseName: {
    fontSize: 16,
    color: "#1f1f1f",
    fontWeight: "800",
  },
  exerciseMeta: {
    color: "#6d6762",
    marginTop: 4,
    fontSize: 13,
  },
  exerciseDescription: {
    color: "#514c46",
    marginTop: 8,
    lineHeight: 20,
  },
  seriesTable: {
    marginTop: 4,
    borderRadius: 18,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#eee2d5",
    overflow: "hidden",
  },
  seriesHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f7efe6",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  seriesHeaderCellBadge: {
    flex: 0.8,
    alignItems: "center",
    justifyContent: "center",
  },
  seriesHeaderCellInput: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  seriesHeaderCellAction: {
    minWidth: 68,
    alignItems: "center",
    justifyContent: "center",
  },
  seriesHeaderText: {
    textAlign: "center",
    color: "#7b736d",
    fontWeight: "700",
    fontSize: 12,
  },
  seriesRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#f2e7db",
    gap: 8,
  },
  seriesRowDone: {
    backgroundColor: "#eff8f3",
  },
  seriesBadge: {
    flex: 0.8,
    alignItems: "center",
  },
  seriesBadgeText: {
    minWidth: 40,
    textAlign: "center",
    backgroundColor: "#2e5dac",
    color: "#fff",
    fontWeight: "800",
    fontSize: 12,
    borderRadius: 10,
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  seriesValue: {
    flex: 1,
    textAlign: "center",
    color: "#1f1f1f",
    fontWeight: "700",
    fontSize: 14,
  },
  seriesLoad: {
    flex: 1,
    textAlign: "center",
    color: "#625b54",
    fontSize: 14,
    fontWeight: "600",
  },
  seriesInput: {
    flex: 1,
    minHeight: 42,
    borderWidth: 1,
    borderColor: "#eadccc",
    borderRadius: 12,
    backgroundColor: "#fffdfb",
    color: "#1f1f1f",
    fontSize: 14,
    paddingHorizontal: 10,
    textAlign: "center",
  },
  seriesToggleButton: {
    minWidth: 68,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d9c9ba",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  seriesToggleButtonDone: {
    backgroundColor: "#1f4037",
    borderColor: "#1f4037",
  },
  seriesToggleText: {
    color: "#2c6e63",
    fontWeight: "800",
    fontSize: 18,
    lineHeight: 18,
  },
  seriesToggleTextDone: {
    color: "#fff",
  },
  seriesFootnote: {
    color: "#6d6762",
    fontSize: 13,
    lineHeight: 19,
  },
  exerciseButtons: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 8,
  },
  goalHeadline: {
    fontSize: 24,
    fontWeight: "800",
    color: "#1f1f1f",
    marginTop: 10,
  },
  progressTrack: {
    height: 12,
    marginTop: 14,
    backgroundColor: "#efe2d6",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#2c6e63",
    borderRadius: 999,
  },
  progressLabel: {
    color: "#6d6762",
    marginTop: 8,
    fontSize: 13,
    fontWeight: "700",
  },
  chartRow: {
    marginTop: 14,
  },
  chartLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  chartLabel: {
    color: "#5b544d",
    fontWeight: "700",
  },
  chartValue: {
    color: "#5b544d",
  },
  chartTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: "#efe3d6",
    overflow: "hidden",
  },
  chartFill: {
    height: "100%",
    borderRadius: 999,
  },
  labelValue: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#efe5da",
  },
  labelValueLabel: {
    color: "#6d6762",
    fontWeight: "700",
  },
  labelValueValue: {
    color: "#1f1f1f",
    fontWeight: "800",
  },
  accentText: {
    color: "#2c6e63",
  },
  emptyText: {
    color: "#7a746e",
    lineHeight: 21,
    marginTop: 10,
  },
  userCard: {
    marginTop: 14,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#faf8f5",
    borderWidth: 1,
    borderColor: "#ece2d6",
  },
  userCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
  },
  userCardInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 17,
    fontWeight: "800",
    color: "#1f1f1f",
  },
  userMeta: {
    color: "#6d6762",
    lineHeight: 20,
    marginTop: 4,
  },
  userRestrictions: {
    color: "#5b544d",
    lineHeight: 20,
    marginTop: 10,
  },
  libraryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#efe6dc",
  },
  libraryInfo: {
    flex: 1,
  },
  libraryTitle: {
    color: "#1f1f1f",
    fontWeight: "700",
    fontSize: 15,
  },
  libraryMeta: {
    color: "#6d6762",
    marginTop: 4,
    lineHeight: 19,
  },
  linkText: {
    color: "#2c6e63",
    fontWeight: "800",
  },
  tabBar: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
    borderRadius: 24,
    backgroundColor: "#1f4037",
    padding: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  tabButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonActive: {
    backgroundColor: "#fff4eb",
  },
  tabButtonText: {
    color: "#dde7e1",
    fontWeight: "800",
    fontSize: 13,
  },
  tabButtonTextActive: {
    color: "#1f4037",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(16, 18, 20, 0.42)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 20,
    maxHeight: "72%",
  },
  modalTitle: {
    fontSize: 22,
    color: "#1f1f1f",
    fontWeight: "800",
  },
  modalSubtitle: {
    color: "#6d6762",
    marginTop: 6,
    lineHeight: 20,
  },
  modalScroll: {
    marginTop: 14,
    marginBottom: 14,
  },
  replacementItem: {
    borderWidth: 1,
    borderColor: "#eedfcf",
    borderRadius: 18,
    padding: 14,
    marginBottom: 10,
    backgroundColor: "#fff9f4",
  },
  replacementTitle: {
    color: "#1f1f1f",
    fontWeight: "800",
    fontSize: 15,
  },
  replacementText: {
    color: "#625b54",
    marginTop: 5,
    lineHeight: 19,
  },
  videoScreen: {
    flex: 1,
    backgroundColor: "#050505",
    paddingTop: 18,
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  videoScreenHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  },
  videoScreenTitle: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "800",
  },
  videoScreenSubtitle: {
    color: "#d7d7d7",
    marginTop: 6,
    lineHeight: 20,
  },
  videoScreenClose: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4f4f4f",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#111",
  },
  videoScreenCloseText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 13,
  },
  videoScreenFrame: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "#000",
  },
  videoWebView: {
    flex: 1,
    backgroundColor: "#000",
  },
});
