import { StyleSheet } from "react-native";

const COLOR = {
  orange: "#ff6a00",
  orangeHot: "#ff3b00",
  orangeSoft: "#ffb26a",
  black: "#171311",
  surface: "#ffffff",
  surfaceAlt: "#fffaf5",
  surfaceRaised: "#fff2e7",
  border: "rgba(32, 24, 18, 0.08)",
  borderStrong: "rgba(32, 24, 18, 0.16)",
  white: "#ffffff",
  offWhite: "#f7f2ec",
  muted: "#766b63",
  mutedSoft: "#9f9085",
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLOR.offWhite,
  },
  loadingScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    backgroundColor: COLOR.offWhite,
    paddingHorizontal: 24,
  },
  loadingText: {
    color: COLOR.muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    fontFamily: "SpaceGrotesk_400Regular",
  },
  authScreen: {
    flexGrow: 1,
    padding: 20,
    justifyContent: "center",
    gap: 16,
    backgroundColor: COLOR.offWhite,
  },
  authHeroPanel: {
    backgroundColor: COLOR.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,106,0,0.18)",
    padding: 20,
    gap: 12,
    shadowColor: "#ff5a00",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 22,
    elevation: 4,
  },
  authAccentLine: {
    width: 46,
    height: 4,
    borderRadius: 999,
    backgroundColor: COLOR.orange,
  },
  authBrandTitle: {
    color: COLOR.white,
    fontSize: 30,
    lineHeight: 34,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  authBrandText: {
    color: COLOR.muted,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  authMetricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  authCard: {
    backgroundColor: COLOR.surfaceAlt,
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    borderColor: COLOR.border,
  },
  authSwitch: {
    alignSelf: "center",
    marginTop: 10,
    paddingVertical: 8,
  },
  authSwitchText: {
    color: COLOR.orange,
    fontSize: 14,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  brandLockup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  brandLockupCompact: {
    gap: 10,
  },
  brandLockupCentered: {
    justifyContent: "center",
    alignSelf: "center",
  },
  brandIconLarge: {
    width: 88,
    height: 88,
    borderRadius: 22,
  },
  brandIconCompact: {
    width: 38,
    height: 38,
    borderRadius: 12,
  },
  brandWordColumn: {
    justifyContent: "center",
  },
  brandWordRow: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  brandWordFat: {
    color: COLOR.black,
    fontSize: 34,
    lineHeight: 38,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  brandWordBurn: {
    color: COLOR.orange,
    fontSize: 34,
    lineHeight: 38,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  brandWordCompact: {
    fontSize: 18,
    lineHeight: 22,
  },
  content: {
    padding: 18,
    paddingBottom: 132,
    gap: 18,
    backgroundColor: COLOR.offWhite,
  },
  registrationContainer: {
    padding: 18,
    gap: 16,
    paddingBottom: 48,
  },
  appHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 14,
    marginBottom: 2,
  },
  brand: {
    color: COLOR.orange,
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: 14,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  headerTitle: {
    color: COLOR.black,
    fontSize: 28,
    lineHeight: 34,
    marginTop: 8,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  headerSubtitle: {
    color: COLOR.muted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  headerAction: {
    minHeight: 44,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: COLOR.surface,
    borderWidth: 1,
    borderColor: COLOR.borderStrong,
    justifyContent: "center",
  },
  headerActionText: {
    color: COLOR.black,
    fontSize: 13,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  heroCard: {
    backgroundColor: COLOR.surface,
    borderRadius: 30,
    padding: 22,
    borderWidth: 1,
    borderColor: "rgba(255,106,0,0.16)",
    shadowColor: "#ff5a00",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 3,
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  heroBrandBadge: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(255,106,0,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,106,0,0.24)",
  },
  heroFocusPill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#fff6ed",
    borderWidth: 1,
    borderColor: COLOR.border,
  },
  heroFocusText: {
    color: COLOR.offWhite,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  heroEyebrow: {
    color: COLOR.orangeSoft,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  heroTitle: {
    marginTop: 18,
    color: COLOR.black,
    fontSize: 32,
    lineHeight: 36,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  heroText: {
    marginTop: 10,
    color: COLOR.muted,
    fontSize: 15,
    lineHeight: 23,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  heroMetricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 16,
  },
  metricChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "#fff6ee",
    borderWidth: 1,
    borderColor: "rgba(255,106,0,0.14)",
  },
  metricChipText: {
    color: COLOR.black,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.7,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  card: {
    backgroundColor: COLOR.surfaceAlt,
    borderRadius: 26,
    padding: 18,
    borderWidth: 1,
    borderColor: COLOR.border,
  },
  highlightCard: {
    backgroundColor: "#fff5ea",
    borderColor: "rgba(255,106,0,0.16)",
  },
  highlightCardAlt: {
    backgroundColor: COLOR.surface,
    borderColor: COLOR.borderStrong,
  },
  highlightEyebrow: {
    color: COLOR.orangeSoft,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.9,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  highlightTitle: {
    color: COLOR.black,
    fontSize: 24,
    lineHeight: 28,
    marginTop: 7,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  highlightText: {
    color: COLOR.muted,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 22,
    lineHeight: 26,
    color: COLOR.black,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  sectionSubtitle: {
    marginTop: 4,
    color: COLOR.muted,
    lineHeight: 21,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  cardTitle: {
    fontSize: 19,
    lineHeight: 23,
    color: COLOR.black,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  cardMiniTitle: {
    fontSize: 13,
    color: COLOR.mutedSoft,
    fontFamily: "SpaceGrotesk_500Medium",
  },
  cardBody: {
    color: COLOR.muted,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  field: {
    marginBottom: 14,
  },
  fieldLabel: {
    fontSize: 13,
    color: COLOR.black,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  input: {
    borderWidth: 1,
    borderColor: COLOR.border,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: COLOR.white,
    color: COLOR.black,
    fontSize: 15,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  inputMultiline: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  segmentedWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  pill: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLOR.border,
    backgroundColor: COLOR.white,
  },
  pillActive: {
    borderColor: COLOR.orange,
    backgroundColor: "rgba(255,106,0,0.16)",
  },
  pillText: {
    color: COLOR.muted,
    fontSize: 13,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  pillTextActive: {
    color: COLOR.white,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 8,
  },
  button: {
    minHeight: 48,
    minWidth: 132,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  buttonFill: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  buttonCompact: {
    flex: 1,
    minHeight: 44,
    minWidth: 0,
  },
  buttonPrimary: {
    backgroundColor: COLOR.orange,
  },
  buttonSecondary: {
    backgroundColor: COLOR.surfaceRaised,
    borderWidth: 1,
    borderColor: COLOR.borderStrong,
  },
  buttonText: {
    fontSize: 14,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  buttonTextCompact: {
    fontSize: 12,
  },
  buttonPrimaryText: {
    color: COLOR.white,
  },
  buttonSecondaryText: {
    color: COLOR.black,
  },
  metricsRow: {
    flexDirection: "row",
    gap: 12,
  },
  metricCard: {
    flex: 1,
    backgroundColor: COLOR.surfaceAlt,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: COLOR.border,
  },
  metricTitle: {
    color: COLOR.mutedSoft,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.7,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  metricValue: {
    color: COLOR.black,
    fontSize: 26,
    lineHeight: 30,
    marginTop: 8,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  metricSubtitle: {
    color: COLOR.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  workoutHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  workoutHeaderLeft: {
    flex: 1,
  },
  workoutSummaryCard: {
    marginTop: 14,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: COLOR.border,
    backgroundColor: COLOR.white,
    padding: 16,
    gap: 8,
  },
  workoutSummaryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  workoutLabel: {
    color: COLOR.orangeSoft,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.9,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  workoutTitle: {
    color: COLOR.black,
    fontSize: 20,
    lineHeight: 24,
    marginTop: 5,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  workoutFocus: {
    color: COLOR.muted,
    marginTop: 6,
    lineHeight: 20,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  workoutGuidance: {
    color: COLOR.muted,
    marginTop: 10,
    lineHeight: 21,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  workoutSummaryText: {
    color: COLOR.muted,
    lineHeight: 20,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    minWidth: 106,
    alignItems: "center",
  },
  statusBadgeActive: {
    backgroundColor: COLOR.orange,
    borderColor: COLOR.orange,
  },
  statusBadgePending: {
    backgroundColor: COLOR.surfaceRaised,
    borderColor: COLOR.borderStrong,
  },
  statusBadgeDone: {
    backgroundColor: "#fff1e3",
    borderColor: "#ffd3b2",
  },
  statusBadgeText: {
    color: COLOR.black,
    fontSize: 11,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.7,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  statusBadgeTextActive: {
    color: COLOR.white,
  },
  statusBadgeTextDone: {
    color: COLOR.black,
  },
  backLink: {
    alignSelf: "flex-start",
    marginBottom: 14,
    paddingVertical: 4,
  },
  backLinkText: {
    color: COLOR.orange,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  tagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  infoNote: {
    color: COLOR.muted,
    marginTop: 12,
    lineHeight: 21,
    backgroundColor: "#fff6ee",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: COLOR.border,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  exerciseItem: {
    marginTop: 14,
    padding: 14,
    borderRadius: 20,
    backgroundColor: COLOR.white,
    borderWidth: 1,
    borderColor: COLOR.border,
    gap: 12,
  },
  exerciseItemDone: {
    borderColor: "rgba(255,106,0,0.36)",
    backgroundColor: "#fff5ea",
  },
  exerciseItemPartial: {
    borderColor: COLOR.borderStrong,
    backgroundColor: "#fffbf7",
  },
  exerciseItemLocked: {
    opacity: 0.8,
  },
  exerciseTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  exerciseInfo: {
    flex: 1,
  },
  exerciseName: {
    fontSize: 17,
    color: COLOR.black,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  exerciseMeta: {
    color: COLOR.orangeSoft,
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: "SpaceGrotesk_500Medium",
  },
  exerciseDescription: {
    color: COLOR.muted,
    marginTop: 8,
    lineHeight: 20,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  seriesTable: {
    marginTop: 4,
    borderRadius: 18,
    backgroundColor: COLOR.surfaceRaised,
    borderWidth: 1,
    borderColor: COLOR.border,
    overflow: "hidden",
  },
  seriesHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff4e8",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  seriesHeaderCellBadge: {
    flex: 0.8,
    alignItems: "center",
    justifyContent: "center",
  },
  seriesHeaderCellInput: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  seriesHeaderCellAction: {
    minWidth: 68,
    alignItems: "center",
    justifyContent: "center",
  },
  seriesHeaderText: {
    textAlign: "center",
    color: COLOR.muted,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  seriesRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "rgba(32, 24, 18, 0.08)",
    gap: 8,
  },
  seriesRowDone: {
    backgroundColor: "rgba(255,106,0,0.08)",
  },
  seriesBadge: {
    flex: 0.8,
    alignItems: "center",
  },
  seriesBadgeText: {
    minWidth: 42,
    textAlign: "center",
    backgroundColor: COLOR.orange,
    color: COLOR.white,
    borderRadius: 10,
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 8,
    fontSize: 12,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  seriesValue: {
    flex: 1,
    textAlign: "center",
    color: COLOR.black,
    fontSize: 14,
    fontFamily: "SpaceGrotesk_500Medium",
  },
  seriesLoad: {
    flex: 1,
    textAlign: "center",
    color: COLOR.muted,
    fontSize: 14,
    fontFamily: "SpaceGrotesk_500Medium",
  },
  seriesInput: {
    flex: 1,
    minHeight: 42,
    borderWidth: 1,
    borderColor: COLOR.borderStrong,
    borderRadius: 12,
    backgroundColor: COLOR.white,
    color: COLOR.black,
    fontSize: 14,
    paddingHorizontal: 10,
    textAlign: "center",
    fontFamily: "SpaceGrotesk_500Medium",
  },
  seriesToggleButton: {
    minWidth: 68,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLOR.borderStrong,
    backgroundColor: COLOR.white,
    alignItems: "center",
    justifyContent: "center",
  },
  seriesToggleButtonDone: {
    backgroundColor: COLOR.orange,
    borderColor: COLOR.orange,
  },
  seriesToggleText: {
    color: COLOR.orange,
    fontSize: 18,
    lineHeight: 18,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  seriesToggleTextDone: {
    color: COLOR.white,
  },
  seriesFootnote: {
    color: COLOR.muted,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  exerciseButtons: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 8,
  },
  goalHeadline: {
    fontSize: 26,
    lineHeight: 30,
    color: COLOR.black,
    marginTop: 10,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  progressTrack: {
    height: 12,
    marginTop: 14,
    backgroundColor: "#eadbcf",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: COLOR.orange,
    borderRadius: 999,
  },
  progressLabel: {
    color: COLOR.muted,
    marginTop: 8,
    fontSize: 13,
    fontFamily: "SpaceGrotesk_500Medium",
  },
  chartRow: {
    marginTop: 14,
  },
  chartLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  chartLabel: {
    color: COLOR.black,
    fontFamily: "SpaceGrotesk_500Medium",
  },
  chartValue: {
    color: COLOR.muted,
    fontFamily: "SpaceGrotesk_500Medium",
  },
  chartTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: "#efdfd1",
    overflow: "hidden",
  },
  chartFill: {
    height: "100%",
    borderRadius: 999,
  },
  labelValue: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(32, 24, 18, 0.08)",
  },
  labelValueLabel: {
    color: COLOR.black,
    flex: 1,
    fontFamily: "SpaceGrotesk_500Medium",
  },
  labelValueValue: {
    color: COLOR.orangeSoft,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  accentText: {
    color: COLOR.orange,
  },
  emptyText: {
    color: COLOR.muted,
    lineHeight: 21,
    marginTop: 10,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  userCard: {
    marginTop: 14,
    padding: 14,
    borderRadius: 18,
    backgroundColor: COLOR.surfaceAlt,
    borderWidth: 1,
    borderColor: COLOR.border,
  },
  userCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
  },
  userCardInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 17,
    color: COLOR.black,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  userMeta: {
    color: COLOR.muted,
    lineHeight: 20,
    marginTop: 4,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  userRestrictions: {
    color: COLOR.muted,
    lineHeight: 20,
    marginTop: 10,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  libraryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(32, 24, 18, 0.08)",
  },
  libraryInfo: {
    flex: 1,
  },
  libraryTitle: {
    color: COLOR.black,
    fontSize: 15,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  libraryMeta: {
    color: COLOR.muted,
    marginTop: 4,
    lineHeight: 19,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  linkText: {
    color: COLOR.orange,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  tabBar: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.96)",
    padding: 8,
    borderWidth: 1,
    borderColor: "rgba(255,106,0,0.18)",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    shadowColor: "#6d3b18",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 8,
  },
  tabButton: {
    flex: 1,
    minHeight: 56,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonActive: {
    backgroundColor: "rgba(255,106,0,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,106,0,0.32)",
  },
  tabButtonIcon: {
    marginBottom: 4,
  },
  tabButtonText: {
    color: COLOR.mutedSoft,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.7,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  tabButtonTextActive: {
    color: COLOR.orange,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.72)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: COLOR.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 20,
    maxHeight: "72%",
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: COLOR.border,
  },
  modalTitle: {
    fontSize: 22,
    lineHeight: 26,
    color: COLOR.black,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  modalSubtitle: {
    color: COLOR.muted,
    marginTop: 6,
    lineHeight: 20,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  modalScroll: {
    marginTop: 14,
    marginBottom: 14,
  },
  replacementItem: {
    borderWidth: 1,
    borderColor: COLOR.border,
    borderRadius: 18,
    padding: 14,
    marginBottom: 10,
    backgroundColor: COLOR.surfaceAlt,
  },
  replacementTitle: {
    color: COLOR.black,
    fontSize: 15,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  replacementText: {
    color: COLOR.muted,
    marginTop: 5,
    lineHeight: 19,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  videoScreen: {
    flex: 1,
    backgroundColor: COLOR.black,
    paddingTop: 18,
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  videoScreenHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  },
  videoScreenTitle: {
    color: COLOR.white,
    fontSize: 24,
    lineHeight: 28,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  videoScreenSubtitle: {
    color: COLOR.muted,
    marginTop: 6,
    lineHeight: 20,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  videoScreenClose: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLOR.borderStrong,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#0f0f0f",
  },
  videoScreenCloseText: {
    color: COLOR.white,
    fontSize: 13,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  videoScreenFrame: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "#000",
    borderWidth: 1,
    borderColor: COLOR.border,
  },
  videoWebView: {
    flex: 1,
    backgroundColor: "#000",
  },
  dialogOverlay: {
    flex: 1,
    backgroundColor: "rgba(23, 19, 17, 0.38)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  dialogCard: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: COLOR.surface,
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: COLOR.border,
    shadowColor: "#6d3b18",
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 10,
  },
  dialogCardError: {
    borderColor: "rgba(255,59,0,0.18)",
  },
  dialogCardSuccess: {
    borderColor: "rgba(255,106,0,0.18)",
  },
  dialogTitle: {
    color: COLOR.black,
    fontSize: 22,
    lineHeight: 26,
    fontFamily: "SpaceGrotesk_700Bold",
  },
  dialogText: {
    marginTop: 10,
    color: COLOR.muted,
    lineHeight: 22,
    fontFamily: "SpaceGrotesk_400Regular",
  },
  dialogActions: {
    marginTop: 18,
  },
});
